name: MobBalance
version: '${project.version}'
main: rezcom.mobbalance.Main
api-version: 1.18
commands:
  MBWolfDebug:
    description: Toggles Wolf debug messages for players with bones in their mouths.
    usage: /MBWolfDebug
    permission: MobBalance.WolfDebug
  MBWolfEXP:
    description: Applies a set EXP value to the closest tamed wolf to the player.
    usage: /MBWolfEXP
    permission: MobBalance.WolfEXP
  MBWolfRandomize:
    description: Randomizes the color of collars of all tamed wolves in a World. Uses only Wild probabilities.
    usage: /MBWolfRandomize
    permission: MobBalance.WolfRandomize
  MBWolfID:
    description: Provides an ID for a wolf.
    usage: /MBWolfID
    permission: MobBalance.WolfID
  MBWolfIDRandomize:
    description: Assigns a random ID to all wolves in a World.
    usage: /MBWolfIDRandomize
    permission: MobBalance.WolfIDRandomize
  MBWolfForceColor:
    description: Forces nearest wolf's color to be target color.
    usage: /MBWolfForceColor <Color>
    permission: MobBalance.WolfForceColor